version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: zimnyaja1/foodgram_backend:latest
    depends_on:
      - db
    env_file: ../.env
    volumes:
      - static:/app/staticfiles
      - media:/app/media

  frontend:
    image: zimnyaja1/foodgram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    image: zimnyaja1/foodgram_gateway
    depends_on:
      - backend
      - frontend
    ports:
      - "8000:80"
    volumes:
      - static:/static
      - media:/media
