version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    build: ../backend
    depends_on:
      - db
    env_file: ../.env
    volumes:
      - static:/app/staticfiles
      - media:/app/media

  frontend:
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    image: nginx:1.25.4-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - media:/media
